version: '3'

services:
  backend:
    container_name: backend
    build: 
      context: backend
      dockerfile: Dockerfile
    image: backend
    env_file:
      - ./.env
    restart: unless-stopped
    ports:
      - "4000:3000"
    networks:
      - backend
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    build: 
      context: frontend
      dockerfile: Dockerfile
    image: frontend
    restart: unless-stopped
    ports:
      - "8081:80"

  postgres:
    container_name: database
    image: postgres:14-alpine
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - pg_data:/data/postgres/
    networks:
      - backend

volumes:
  pg_data:
    driver: local

networks:
  backend: {}